on:
  push:
    branches: [main]
  schedule:
    - cron: '42 5 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - uses: DeterminateSystems/nix-installer-action@90bb610b90bf290cad97484ba341453bd1cbefea # v19
      - run: nix flake update
        if: ${{ github.event_name == 'schedule' }}
      - run: nix build .
      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
        with:
          name: all-nix-docsets
          path: result/*.docset
          if-no-files-found: "error"
      - id: pages
        uses: actions/configure-pages@v5
      - run: nix build .#index
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./result

  deploy_to_pages:
    needs: build_index
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
